
var nofn = [
  "Marín Lilja Ágústsdóttir",
  "Friðrik Árni Halldórsson",
  "Gunnar Francis Schram",
  "Guðrún Höskuldsdóttir",
  "Guðrún Höskuldsdóttir",
  "Snjólaug Heimisdóttir",
  "Kristjana Björk Barðdal",
  "Auður Ásta Baldursdóttir",
  "Ingvar Haukur Jóhannsson",
  "Heiðar Már Þráinsson",
  "Brynjar Ingimarsson",
  "Sigurður Andri Jóhannesson",
  "Gísli Georgsson",
  "Vífill Harðarson",
  "Stefán Gunnlaugur Jónsson",
  "Ísak Sigfússon",
  "Herbert Vilhjalmsson",
  "Kristján Jónsson",
  "Sverrir Heiðar Davíðsson",
  "Baldur Geir Gunnarsson",
  "Aron Tryggvi Johannesson",
  "Kara Magnúsdóttir",
  "Tómas Helgi Hjartarson",
  "Máni Sveinn Þorsteinsson",
  "Bjarki Bernardsson",
  "Kári Torfason",
  "Kristján Örn Aðalbjörnsson",
  "Þórður Jónsson",
  "Magnea Haraldsdóttir",
  "Nína Lea Z. Jónsdóttir",
  "Atli Þór Helgason",
  "Óðinn Kári Rúnarsson",
  "Jónas Páll Grétarsson",
  "Kjartan Magnússon",
  "Laufey Þóra Borgþórsdóttir"
];
